### ISSUE TITLE
I have a build failure problem

### ISSUE THREAD

**Issue by tongzv001** [kanru/hhkb-zmk#10]
I have a build failure problem but I don't know how to solve it, could you please help me
![image](https://github.com/kanru/hhkb-zmk/assets/128016494/bea905e9-6230-47eb-aec5-ac10ad30259f)

**Comment by kanru** [comment]
Can you share your repository?

**Comment by tongzv001** [comment]
Can you get a copy of the UF2 file that you successfully built? If possible, please send it to this email：tongzv1998@gmail.com

**Comment by tongzv001** [comment]
Can you send the built UF2 file? If possible, please send to this email：tongzv1998@gmail.com

**Comment by kanru** [comment]
You can download it from previous CI builds https://github.com/kanru/hhkb-zmk/actions/runs/7850667311

It might not work if your pinout is different.

**Comment by tongzv001** [comment]
Thanks
